-- ============================================================
-- TenantSentry.ai — Migration 010
-- F16: Anomaly flag table
--
-- Stores per-invoice anomaly flags generated by
-- services/anomaly_monitor.py. Each flag represents a
-- detected billing anomaly: wrong charge type, CPI variance,
-- unexpected category, period-on-period spike, etc.
--
-- Tenants can dismiss flags they've reviewed.
-- Safe to run multiple times.
-- ============================================================

CREATE TABLE IF NOT EXISTS anomaly_flag (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id          TEXT        NOT NULL,
    invoice_id      UUID        REFERENCES invoice(id) ON DELETE CASCADE,

    -- Which check fired
    check_name      TEXT        NOT NULL,
    -- e.g. "category_cost_spike" | "cpi_variance" | "prohibited_category" |
    --      "amount_exceeds_cap" | "duplicate_period" | "new_category" |
    --      "outgoings_creep" | "invoice_frequency"

    -- What was affected
    category        TEXT,                       -- charge category name from invoice

    -- Severity drives alert behaviour
    severity        TEXT        NOT NULL
                                CHECK (severity IN ('high', 'medium', 'low')),

    -- Plain English explanation shown to tenant
    description     TEXT,

    -- Financial context for the flag
    expected_cents  BIGINT,                     -- what the lease / history predicts
    actual_cents    BIGINT,                     -- what the invoice claims
    delta_pct       NUMERIC(6, 2),              -- percentage variance (NULL if not applicable)

    -- Tenant dismissal
    dismissed       BOOLEAN     DEFAULT FALSE,
    dismissed_at    TIMESTAMPTZ,
    dismissed_note  TEXT,                       -- optional tenant note on dismissal

    -- Layer that generated this flag: 'rule' (Layer 1) or 'trend' (Layer 2)
    detection_layer TEXT        DEFAULT 'rule'
                                CHECK (detection_layer IN ('rule', 'trend')),

    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_anomaly_job_id     ON anomaly_flag (job_id);
CREATE INDEX IF NOT EXISTS idx_anomaly_invoice_id ON anomaly_flag (invoice_id);
CREATE INDEX IF NOT EXISTS idx_anomaly_severity   ON anomaly_flag (severity)
    WHERE dismissed = FALSE;
CREATE INDEX IF NOT EXISTS idx_anomaly_active     ON anomaly_flag (job_id, created_at DESC)
    WHERE dismissed = FALSE;

-- RLS
ALTER TABLE anomaly_flag ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'anomaly_flag' AND policyname = 'service_role_all'
    ) THEN
        CREATE POLICY "service_role_all" ON anomaly_flag
            FOR ALL TO service_role USING (true) WITH CHECK (true);
    END IF;
END $$;

-- ============================================================
-- Verify:
--   SELECT * FROM anomaly_flag LIMIT 5;
--   SELECT check_name, severity, COUNT(*) FROM anomaly_flag
--   GROUP BY 1, 2 ORDER BY 3 DESC;
-- ============================================================
